name: latest-build
on:
  push:
    branches:
      - main
      - master
jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd python
          cp -f env_matrix/python-${{ matrix.python_version}}.env .env
          source .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: python
          file: python/Dockerfile
          push: true
          tags: lucernae/python-ci-agent:${{ matrix.python_version }}
          build-args: |
            BASE_IMAGE=python:${{ matrix.python_version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
